# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da09c4bb7f612ffebac73917e76f5bd099fc436db30db46cbf6c42c1d60aeb34a691afc1ab16b51896c1e91ca6384e93f5519307cae68d14a56d88bbdb6703ca

test:
  secret_key_base: f05a9f1fa681030775f6fc9650f4fa5bca242e575dabd58048e027a0810bfadd121eb57346f6713e6f0bc6f51167ab32c36332c8a0fb9dba2645df5b2affc523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
